SELECT 
TBL.TABLE_TYPE,
COL.TABLE_NAME,
COL.ORDINAL_POSITION,
COL.COLUMN_NAME,
COL.DATA_TYPE,
COL.IS_NULLABLE,
ISNULL(COL.CHARACTER_MAXIMUM_LENGTH,-1) AS MAXIMUM_LENGTH,
COL.TABLE_CATALOG,
COL.TABLE_NAME,
(
	CASE COLUSAGE.COLUMN_NAME
		WHEN COL.COLUMN_NAME THEN 'YES'
		ELSE 'NO'
		END
)AS PRIMARY_KEY,
FOREIGN_KEY.FOREIGN_TABLE,
FOREIGN_KEY.FOREIGN_COLUMN

FROM INFORMATION_SCHEMA.COLUMNS COL
JOIN
INFORMATION_SCHEMA.VIEWS TBL
ON
COL.TABLE_NAME=TBL.TABLE_NAME
JOIN
INFORMATION_SCHEMA.TABLE_CONSTRAINTS TBLCONST
ON
TBLCONST.TABLE_NAME = COL.TABLE_NAME
JOIN
INFORMATION_SCHEMA.VIEW_COLUMN_USAGE COLUSAGE
ON
COLUSAGE.CONSTRAINT_NAME = TBLCONST.CONSTRAINT_NAME
AND
TBLCONST.TABLE_NAME = COL.TABLE_NAME
--FOREIGN KEYS
LEFT JOIN
(
SELECT 
A.TABLE_NAME,
A.COLUMN_NAME,
C.TABLE_NAME FOREIGN_TABLE,
C.COLUMN_NAME FOREIGN_COLUMN
FROM INFORMATION_SCHEMA.VIEW_COLUMN_USAGE A
JOIN  
INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS B
ON
A.CONSTRAINT_NAME=B.CONSTRAINT_NAME
JOIN
INFORMATION_SCHEMA.VIEW_COLUMN_USAGE C
ON
C.CONSTRAINT_NAME=B.UNIQUE_CONSTRAINT_NAME
) FOREIGN_KEY

ON
COL.COLUMN_NAME = FOREIGN_KEY.COLUMN_NAME